[package]
name = "generics"
version = "0.1.0"
edition = "2021"
authors = ["clouds"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aggregator"
path = "src/lib.rs"

[dependencies]
